### ISSUE TITLE
Mismatch in administrative_role privilege targets

### ISSUE THREAD

**Issue by hobietje** [appgate/terraform-provider-appgatesdp#115]
When trying to setup an appgate_administrative_role with specific privileges, we cannot add **OnBoardedDevice** / **RegisteredDevice**.  TF provider seems to except one but API accepts only the other.

---

Error: Could not create Administrative role Validation error Validation failed. 
 privileges[5].target **OnBoardedDevice** was not one of [All, Appliance, Condition, CriteriaScript, Entitlement, AdministrativeRole, IdentityProvider, MfaProvider, IpPool, LocalUser, Policy, Site, DeviceClaimScript, EntitlementScript, RingfenceRule, ApplianceCustomization, TrustedCertificate, DnsClassification, DnsRule, UserClaimScript, OtpSeed, Fido2Device, TokenRecord, Blacklist, License, UserLicense, **RegisteredDevice**, AllocatedIp, SessionInfo, AuditLog, AdminMessage, GlobalSetting, CaCertificate, File, FailedAuthentication, Stats]

vs

Error: type must be on of [All Appliance Condition CriteriaScript Entitlement AdministrativeRole IdentityProvider MfaProvider IpPool LocalUser Policy Site DeviceScript EntitlementScript RingfenceRule ApplianceCustomization OtpSeed TokenRecord Blacklist UserLicense **OnBoardedDevice** AllocatedIp SessionInfo AuditLog AdminMessage GlobalSetting CaCertificate File FailedAuthentication], got **RegisteredDevice**

**Comment by danijeel** [comment]
hey, thanks to noticing this, its indeed a bug, this will be fixed in an upcoming release. `OnBoardedDevice` has been removed in favor for `RegisteredDevice`
