### ISSUE TITLE
spa mode disabled produces errors

### ISSUE THREAD

**Issue by drewmullen** [appgate/terraform-provider-appgatesdp#117]
```
resource "appgatesdp_appliance" "template_gateway" {
  client_interface {
    ...
    override_spa_mode = "Disabled"
  }
}
```

yields:
```
│ Error: Could not create appliance Validation error Validation failed.
│  clientInterface.overrideSpaMode Disabled was not one of [TCP, UDP_TCP]
```

```
$ tf version
Terraform v0.15.3
on linux_amd64
+ provider registry.terraform.io/appgate/appgatesdp v0.5.1
```

**Comment by danijeel** [comment]
hey @drewmullen , yes nice catch. there was an error in the api specification, `Disabled` has been removed, If you don't want to override, omit `override_spa_mode`. I will update the documentation for this.

**Comment by drewmullen** [comment]
unfortunately, thats how i first found the error :sob: 

```
    # override_spa_mode = "TCP"

 Error: Could not create appliance Validation error Validation failed.
│  clientInterface.overrideSpaMode  was not one of [TCP, UDP_TCP]
```

FWIW - "Disabled" might be a better solution since TF doesnt really gracefully handle attribute omission. We're putting this configuration in a module and passing values to define templates, passing "Disabled" as a variable would be much easier

**Comment by danijeel** [comment]
What version of appliances are you using?

**Comment by drewmullen** [comment]
5.3.2-23587

**Comment by danijeel** [comment]
thanks, after debugging this further I found the issue (it accidentally sent overrideSpaMode as a empty string in the payload) this has been fixed in https://github.com/appgate/terraform-provider-appgatesdp/pull/119. I will do another release once its merged.

**Comment by drewmullen** [comment]
Can we talk about including the `Disabled` as an option instead of omitting the parameter? IMO thats a much cleaner solution

**Comment by danijeel** [comment]
I will see if can come up with a suitable implementation for this next week. It easier to keep an 1:1 relationship with the state file and the API response, but maybe we can do a workaround for this.

**Comment by danijeel** [comment]
Closing this issue, as of [0.5.4](https://github.com/appgate/terraform-provider-appgatesdp/releases/tag/v0.5.4) we will allow disabled for `override_spa_mode`.
