### ISSUE TITLE
imported appgatesdp_site do not accurately reflect the snat value

### ISSUE THREAD

**Issue by drewmullen** [appgate/terraform-provider-appgatesdp#121]
in order to figure out the parameters to populate in terraform (how terraform attributes map to appgate gui values) i imported a site then compared to a diff (`plan`). This is a common pattern for learning how attribute names map from api -> terraform.

the snat defaults to false but the site I imported had the value as true, the computed value change does not show in the `terraform plan` diff based on the default value. this is likely true for all `vpn {}` values but I only noticed `snat` (it caused me a headache by not realizing it was set improperly)

```
  # appgatesdp_site.appgate will be updated in-place
  ~ resource "appgatesdp_site" "appgate" {
      - description               = "dev environment." -> null
        id                        = "<UUID>"
      ~ name                      = "Lab" -> "drew site"
      ~ notes                     = "Built-in default site." -> "Appgate site for drew"
      ~ short_name                = "LAB" -> "drew"
      ~ tags                      = [
          + "drew",
          + "terraform",
        ]
```

I would expect the plan above to include:
```
 vpn {
    ~ snat = true -> false
```

i dont necessarily think this is a big bug but it caused me some pain for a couple hours because i didnt realize that setting was different between the imported site and the one i created later. figured i'd report and yall can prioritize however you want

to replicate:
1. create a site in the gui, make sure the snat value is UNCHECKED
2. import the resource to terraform `terraform import appgatesdp_site.gbg_site  <site id>`
3. `terraform plan` with a resource that has no `vpn` section defined

----------
on an unrelated note, if you specify the `vpn {}` it sets a value that i cannot find in the site gui `web_proxy_verify_upstream_certificate = true`

**Comment by drewmullen** [comment]
i have also confirmed this morning that `plan` diff does not show name resolver data too

im guessing this is the case for all complex data types (block values within the site resource)

**Comment by drewmullen** [comment]
there seem to be general issues with the `vpn` block. every time i run apply it attempts to change in place:

```
  # module.appgate_config.appgatesdp_site.appgate will be updated in-place
  ~ resource "appgatesdp_site" "appgate" {
        id                        = "<uuid>"
        name                      = "acme site"
        tags                      = [
            "acme",
            "dev",
            "terraform",
        ]
        # (6 unchanged attributes hidden)



      - vpn {
          - ip_access_log_interval_seconds        = 0 -> null
          - snat                                  = true -> null
          - state_sharing                         = false -> null
          - web_proxy_enabled                     = false -> null
          - web_proxy_verify_upstream_certificate = false -> null

          - dtls {
              - enabled = false -> null
            }

          - tls {
              - enabled = true -> null
            }
        }
      + vpn {
          + snat                                  = true
          + state_sharing                         = false
          + web_proxy_verify_upstream_certificate = false
        }
        # (2 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

hcl:
```
resource "appgatesdp_site" "appgate" {
  name                      = "acme site"
  short_name                = "acme"
  tags                      = local.appgate_tags
  entitlement_based_routing = true

  notes = "Appgate site"

  vpn {
    state_sharing = false
    snat = true
    web_proxy_verify_upstream_certificate = false
  }

  network_subnets = []
  default_gateway {
    enabled_v4       = false
    enabled_v6       = false
    excluded_subnets = []
  }
}
```

**Comment by drewmullen** [comment]
playing around with this a little, if i set all values (do not rely on defaults) then terraform plan does not detect change required. if i had to guess, when you perform the api read, youre not accounting for the potential default values and then your diff on the declared state is detecting the change:

```
  vpn {
    state_sharing = false
    snat = true
    web_proxy_enabled = false
    web_proxy_verify_upstream_certificate = false
    ip_access_log_interval_seconds = 0
    dtls {
        enabled = false
    }

    tls {
        enabled = true
    }
  }
```

**Comment by danijeel** [comment]
I was not able to reproduce this.

When I do imports, I usually use terraform import in combination with [terraform state show](https://www.terraform.io/docs/cli/commands/state/show.html)

```bash
terraform init
```
define the import resource in a tf file.
```hcl
resource "appgatesdp_site" "gbg_site" {}
```

```bash
terraform import appgatesdp_site.gbg_site <site id>
```
```bash
terraform state show 'appgatesdp_site.gbg_site' 
```

copy the output from stdout and paste it to .tf file, and remove computed values, such as site_id, id.

> on an unrelated note, if you specify the vpn {} it sets a value that i cannot find in the site gui web_proxy_verify_upstream_certificate = true

this option is only in 5.3
![image](https://user-images.githubusercontent.com/1218385/119823715-6b378e00-bef5-11eb-9954-6ebaa18ae3da.png)

**Comment by drewmullen** [comment]
`show` actually is better for populating starting values!

There is still an issue with the vpn block though, here is a clearer way to show you the issue:

1. using terraform, create a site with the vpn block below. notice that `snat` is not the default value
2. after the site is created, comment out the vpn block and run `tf plan` -> `No changes. Infrastructure is up-to-date.` you would expect either removal of the vpn block or change to the defaults.


```
  vpn {
    state_sharing = false
    snat = true
    web_proxy_enabled = false
    web_proxy_verify_upstream_certificate = false
    ip_access_log_interval_seconds = 0
    dtls {
        enabled = false
    }
    tls {
        enabled = true
    }
  }
```
