### ISSUE TITLE
appliance_customization only checks changes in file names and not contents

### ISSUE THREAD

**Issue by stephengroat-dd** [appgate/terraform-provider-appgatesdp#130]
https://github.com/appgate/terraform-provider-appgatesdp/blob/7704c44c61c75a96e2eb355e79fb04c829746458/appgate/resource_appgate_appliance_customization.go#L160-L179

This code only checks for changes in the `file` param, which is the file name, not the `checksum_sha256`, which checks the contents

Needs to read the file, check the sha256, determine if changes, and then update accordingly

**Comment by danijeel** [comment]
this has been resolved in [0.5.6](https://github.com/appgate/terraform-provider-appgatesdp/releases/tag/v0.5.6)
