### ISSUE TITLE
Error: Failed to read Appliance, 404 Not Found

### ISSUE THREAD

**Issue by stephengroat-dd** [appgate/terraform-provider-appgatesdp#152]
https://github.com/appgate/terraform-provider-appgatesdp/blob/fc69b922f95dd6b9d4dc8293d60c1d90ec311a25/appgate/resource_appgate_appliance.go#L1474-L1477

when an appliance is deleted in the UI but left in the state, the provider errors

shouldn't the behavior assume that a `404` means that the resource is not found and needs to be recreated? a la https://github.com/hashicorp/terraform-provider-aws/blob/main/aws/resource_aws_accessanalyzer_analyzer.go#L118-L124

this behavior should probably be replicated for all resources

**Comment by danijeel** [comment]
Hi @stephengroat-dd , yes that make sense, good idea.
