### ISSUE TITLE
update v15 API to use int64 for ip_pool total

### ISSUE THREAD

**Issue by stephengroat-dd** [appgate/terraform-provider-appgatesdp#172]
https://github.com/appgate/sdp-api-specification/pull/2/files

needs to be merged and applied to TF provider, currently getting errors unmarshalling `total` field for v6 on a data block

```
Error: json: cannot unmarshal number 18446744073709551868 into Go struct field IpPool.data.total of type int32
  with module.identity_providers.data.appgatesdp_ip_pool.default_ip_pool["6"],
  on identity_providers/main.tf line 9, in data "appgatesdp_ip_pool" "default_ip_pool":
   9: data "appgatesdp_ip_pool" "default_ip_pool" {
```

**Comment by danijeel** [comment]
Thanks for reporting this issue, this has been resolved in [0.6.13](https://github.com/appgate/terraform-provider-appgatesdp/releases/tag/v0.6.13)
