### ISSUE TITLE
Support sending provider through proxy

### ISSUE THREAD

**Issue by infosec-shinobi** [appgate/terraform-provider-appgatesdp#187]
Can you support sending the provider through a proxy for those of us that leverage Terraform Enterprise and/or need to run TF locally behind a corporate proxy?

We added support for this in our local version of the provider when we first started to do this. A co-worker will be submitting a PR with the logic.

**Comment by infosec-shinobi** [comment]
@dirtyonekanobi

**Comment by thomascellerier** [comment]
If you submit a PR to add support for this we will definitely accept it.
Is this a standard HTTP/HTTPS proxy?

**Comment by infosec-shinobi** [comment]
@thomascellerier , you should be getting a pr in the coming days from @dirtyonekanobi . 

We added this support to our local provider and forgot to include it in our previous PRs to you. Working on migrating to the hosted provider now so we can move away from the locally compiled one and realized the proxy variable wasn't recognized with the provider anymore.

Correct, this would be standard http/https proxy.

**Comment by danijeel** [comment]
I had some spare time over, so I implemented this in #196 

You can use this with environment variable `HTTP_PROXY="http://proxyIp:proxyPort"` this will remain an undocumented feature for now.
