### ISSUE TITLE
Support Additional Controllers

### ISSUE THREAD

**Issue by SPSeanLong** [appgate/terraform-provider-appgatesdp#188]
Appgate 5.4+ validation prevents defining additional appliances as controllers that would be needed to provide HA

Workflow is:
     Create appliance
     Seed appliance successfully
     Update appliance definition via API/UI to add controller role

Currently the options to do this seem to be:
1. null_resource to use script which polls API & validate when appliance is healthy. Then null_resource to use script adjust appliance definition via API
2. embeded a script into the userdata field of appliance to wait until healthy & then call API and adjust appliance definition

Both of these may cause a delta between current status & the tf state file for the appliance

Request:
- Custom is_controller attribute (or something similar) which allows the provider to handle this use-case

Benefits:
- Avoids custom/direct use of the API reduces the number of locations for the password to be discovered
- Prevents users from custom developing the same workarounds

**Comment by danijeel** [comment]
Closing this issue, since an solution for this problem as been implemented. https://registry.terraform.io/providers/appgate/appgatesdp/latest/docs/guides/ha_controllers
