### ISSUE TITLE
appgate_insecure property in config.json no longer respected in 8.0

### ISSUE THREAD

**Issue by SPSeanLong** [appgate/terraform-provider-appgatesdp#189]
appgateprovider.config.json has been using the "appgate_insecure":true but since upgrading the 8.0 provider we now see the following issue:

`Error: Error create: Import certificate or toggle APPGATE_INSECURE - x509: certificate signed by unknown authority`

Workaround: Export variable every few hours still works
   `export APPGATE_INSECURE="true"`

**Comment by danijeel** [comment]
that is intended behavior, https://registry.terraform.io/providers/appgate/appgatesdp/latest/docs#config-file

We have limited number of variables that can be defined in the config file, right now only the following keys are alllowed in the config file

the following keys are allowed within the config file, all keys are optional.
```json

{
    "appgate_url": "string",
    "appgate_username": "string",
    "appgate_password": "string",
    "appgate_provider": "string",
    "appgate_bearer_token": "string",
    "appgate_client_version": 16,
}
```
