### ISSUE TITLE
route_via ipv4 and ipv6 should be optional

### ISSUE THREAD

**Issue by infosec-shinobi** [appgate/terraform-provider-appgatesdp#198]
https://github.com/appgate/terraform-provider-appgatesdp/blob/1f61640bf90b4e2235a8957777aff334c419b8aa/appgate/resource_appgate_site.go#L188

Per your docs (https://registry.terraform.io/providers/appgate/appgatesdp/latest/docs/resources/site#route_via)
![image](https://user-images.githubusercontent.com/44758807/146581396-60b03d25-49bc-49b7-88e8-c643d131c583.png)

and our implementation, you should be able to only provide ipv4 without an error thrown but i looks like ipv6 (and ipv4) are noted as required in the code resulting in an error when trying to just set ipv4...

![image](https://user-images.githubusercontent.com/44758807/146581530-f41215a1-06ed-485a-92f6-82625ea51ab7.png)

I think I might be able to mask it with a null value.

**Comment by danijeel** [comment]
Closing this issue, this should be resolved in [v0.8.4](https://github.com/appgate/terraform-provider-appgatesdp/releases/tag/v0.8.4)
