### ISSUE TITLE
Identification new appliance has reached healthy state 

### ISSUE THREAD

**Issue by SPSeanLong** [appgate/terraform-provider-appgatesdp#200]
When deploying new appliances there is no way to identify if it has reached its final healthy state

Creating a collective with 5 appliances currently has a flow:
- Create first appliance
- Create additional appliances 2-5
- Terraform completes
- Minutes pass
- Machines are provisioned 
- Machines become active in collective with possible error or warning state
- Machines become healthy
- Environment has reached end-state as configured by terraform

Requesting a way to wait or check that an appliance seeding has completed. Alternatively a data source to get the auth token so custom scripts can be run in provisioners without the need for additional credential management & auth requests.

**Comment by danijeel** [comment]
Hi @SPSeanLong, I've not come up with a native tf resource/data source that would solve this, however I've tested some things locally and i came up with the following script to check if the status of the seed has completed and reached a healthy state.



```hcl
resource "null_resource" "seed_appliance" {
  depends_on = [
    appgatesdp_appliance.another_gateway,
  ]

  connection {
    type        = "ssh"
    user        = "cz"
    timeout     = "25m"
    private_key = file(var.private_key)
    host        = aws_instance.another_gateway.public_dns
  }

  provisioner "local-exec" {
    command = "echo ${data.appgatesdp_appliance_seed.another_gateway_seed.seed_file} > seed.b64"
  }
  provisioner "file" {
    source      = "seed.b64"
    destination = "/home/cz/seed.b64"
  }
  # inital seeding of the appliance
  provisioner "remote-exec" {
    inline = [
      "cat seed.b64 | base64 -d  | jq .  >> seed.json",
      // wait for the seed to get picked up and initialized
      "sleep 60",
      "echo OK",
    ]
  }
  # After the appliance has been seeded, we will wait until the new appliance has reached healthy status, if not fail.
  provisioner "local-exec" {
    command = "/absolute/path/for/script/statuscheck ${appgatesdp_appliance.another_gateway.id}"
    environment = {
      APPGATE_CONFIG_PATH    = var.appgate_config_file
      APPGATE_CLIENT_VERSION = 16
    }
  }
}

```
the statuscheck script in this case is a go program, statuscheck 
https://gist.github.com/danijeel/b7b0207a3c2a8d638ead15e3af1da8a0 
you can ofcourse edit this to your own needs (or translate it to another language for example bash/python or something), the only thing it does is that it retries `HTTP GET /stats/appliances` for 5 minutes or until it reached healthy status and exit with exitcode 0, otherwise exitcode 1.

**Comment by SPSeanLong** [comment]
Wanted to avoid opening port 22 to the appliances. 

For first controller the appliance is assumed healthy 60 seconds after the admin-portal starts responding
```
resource "null_resource" "farm_init"{
  // 406 response when API successfully rejects call for missing Appgate headers. 
  // App portal init faster than db, sleep extra 60 to ensure db is ready 
  // TODO: Add max tries to avoid infinite loop 
  provisioner "local-exec" {
    command = "check_status=true; while($check_status); do status=$(curl -X POST -k -s -o /dev/null -I -w %%{http_code} https://${local.ctrl1_dns_record}:8443/admin/login); if [[ \"$status\" -ne 406 ]]; then check_status=true; sleep 3; else check_status=false; fi; done; sleep 60"
  }
  depends_on = [
    module.appgate_first_appliance
  ]
} 
```
For additional appliances a python script is called by tf that waits until the # of active appliances = number of appliances defined in the system
