### ISSUE TITLE
Peer Interface being removed but still required

### ISSUE THREAD

**Issue by infosec-shinobi** [appgate/terraform-provider-appgatesdp#210]
https://github.com/appgate/terraform-provider-appgatesdp/blob/2375d6b1f7edd8d37bab1d25c76202bacba42518/appgate/resource_appgate_appliance.go#L141

Any thoughts on when this will be flipped to optional and/or removed?

**Comment by danijeel** [comment]
Hello @infosec-shinobi , It will be removed in Appgate SDP v6.0 (The next major version, being released later this spring).
