### ISSUE TITLE
appgatesdp_policy.dns_settings isn't removed correctly

### ISSUE THREAD

**Issue by hobietje** [appgate/terraform-provider-appgatesdp#211]
### Terraform CLI, Terraform appgatesdp Provider Version, and Appgate Appliance version(s)

terraform cli: v0.14.4
terraform-provider-appgatesdp:  0.8.5
appgate appliance version: 5.5.2

### Affected Resource(s)

appgatesdp_policy

### Terraform Configuration Files

Before:

```hcl
resource "appgatesdp_policy" "dns" {
  name  = "Forward DNS"
  disabled = false

  dns_settings {
    domain = "default"
    servers = concat(
      tolist(data.aws_route53_resolver_endpoint.dns_aws_oregon.ip_addresses),
    )
  }
  
  entitlements = [
    appgatesdp_entitlement.dns_aws.id,
  ]
}
```

After:

```hcl
resource "appgatesdp_policy" "dns" {
  name  = "Forward DNS"
  disabled = false

  entitlements = [
    appgatesdp_entitlement.dns_aws.id,
  ]
}
```

### Expected Behavior

Default `dns_settings` should be removed from SDP policy

### Actual Behavior

Default `dns_settings` continue to be applied to the SDP policy

### Steps to Reproduce

1. Deploy a policy with `dns_settings` configured
2. Update the policy with the `dns_settings` block(s) removed

### Important Factoids

This is following an upgrade from v5.2 to v5.5 where we are trying to take advantage of the new `domain://` syntax.  We applied some changes for the new DNS policies which we later tried to roll back.  The rollback appeared successful however we found out through Appgate SDP Client logs that the settings are still applied.

**Comment by danijeel** [comment]
Thanks for reporting this, this should be resolved in [0.8.7](https://github.com/appgate/terraform-provider-appgatesdp/releases/tag/v0.8.7 )
