### ISSUE TITLE
gateway block breaks appliance validation due to netmask 

### ISSUE THREAD

**Issue by SPSeanLong** [appgate/terraform-provider-appgatesdp#212]
+ provider registry.terraform.io/appgate/appgatesdp v0.8.6

After upgrading from provider 0.8.2 to 0.8.6 terraform is unable to deploy additional appliance when gateway block is present. I have added netmask = 0 to gateway.vpn.allowDestinations[0] and still receive error:

`
Error: Could not create appliance Validation error Validation failed. 
│  gateway.vpn.allowDestinations[0].netmask must be configured if address is set.`

code segment working in 0.8.2
```
variable "is_gateway" {
  type = bool
  default = false
}

resource "appgatesdp_appliance" "appliance_definition"{
	name = var.friendly_name
	hostname = aws_eip.appliance_ip.public_dns
	site = data.appgatesdp_site.default_site.id
	gateway {
		enabled = var.is_gateway
		vpn {
		  allow_destinations {
			address = "0.0.0.0"
			netmask = 0
			nic     = "eth0"
		  }
		}
	  }
```

current workaround
```
dynamic "gateway" {
    for_each = var.is_gateway ? ["gateway_role_true"]:[]
    content{
        enabled = var.is_gateway
        vpn {
             allow_destinations {
            address = "0.0.0.0"
            netmask = 0
            nic     = "eth0"
      }
   }
}
```

**Comment by danijeel** [comment]
thanks for reporting, this should be fixed in [0.8.8](https://github.com/appgate/terraform-provider-appgatesdp/releases/tag/v0.8.8)
