### ISSUE TITLE
Import encounters issue

### ISSUE THREAD

**Issue by SPSeanLong** [appgate/terraform-provider-appgatesdp#219]
Documentation shows admin-roles can be imported with: ` terraform import appgatesdp_administrative_role <id>`

result:
```
 terraform import appgatesdp_administrative_role b6a96ee6-18ec-4af6-b95c-06616bd6ca7f
╷
│ Error: Invalid address
│
│   on <import-address> line 1:
│    1: appgatesdp_administrative_role
│
│ Resource specification must include a resource type and name.
╵
```

**Comment by danijeel** [comment]
Hi @SPSeanLong,

The documentation for import was missing dot notation for resource name.
the correct syntax would be

```sh
terraform import appgatesdp_administrative_role.example <id>
```
where `example` is the name of the pre-defined resource in a terraform file
and `<id>` is the resource ID, normally a UUID


for example, in your main.tf you have a defined a `administrative_role` called `admin`

```hcl
resource "appgatesdp_administrative_role" "admin" {}
```

Then you can run 
```bash
terraform import appgatesdp_administrative_role.admin UUID
```

For more info about import you can see terraform documentation
- https://www.terraform.io/cli/commands/import
- https://www.terraform.io/cli/import

The documentation will be update to reflect this in https://github.com/appgate/terraform-provider-appgatesdp/pull/223 and will be included in the next release.


a helpful tips for import is after you run your `terraform import` command you can run
```bash
terraform state show 'appgatesdp_administrative_role.admin' 
```
and that will print the HCL configuration to stdout, this result can be simple copy pasted into your .tf file. Next time you run terraform plan you should not see any changes for this resource.
