### ISSUE TITLE
[Feature Request] User Claim Script: Terraform Resource

### ISSUE THREAD

**Issue by ashwinnirantar** [appgate/terraform-provider-appgatesdp#239]
### Doubt

I am looking to create a user claim script to be run by the Controller in Terraform, however there seems to be no terraform resource for this. Can someone confirm if this is on the roadmap? What is the recommended method for creating user claim scripts? 

[Appgate SDP Terraform Provider](https://registry.terraform.io/providers/appgate/appgatesdp/latest/docs)

**Comment by danijeel** [comment]
Thanks for reporting it, I will add this in the upcoming release.

**Comment by danijeel** [comment]
This is now available in [v0.8.12](https://github.com/appgate/terraform-provider-appgatesdp/releases/tag/v0.8.12) https://registry.terraform.io/providers/appgate/appgatesdp/0.8.12

**Comment by ashwinnirantar** [comment]
Thats great, thank you @danijeel!! Really appreciate it. Also, do you have any more examples/documentation on user claim scripts? Trying to implement a solution where we need external HTTP calls to AWS, but would like some examples around how authentication can be achieved. Thanks

**Comment by gokhan-berberoglu** [comment]
@ashwinnirantar you can find examples on how to query a rest api here:

https://sdphelp.appgate.com/adminguide/v6.0/external-calls.html

there is an example there showing how to login to a controller, it may give you some inspiration. 

otherwise feel free to contact support@appgate.com

**Comment by ashwinnirantar** [comment]
> 

Thank you @gokhan-berberoglu. Quick question, where will I be able to see the console log output? 

e.g. `console.log(allocations);`

**Comment by gokhan-berberoglu** [comment]
when you Test, it'll be visible on the test results page.

**Comment by ashwinnirantar** [comment]
> when you Test, it'll be visible on the test results page.

Got it, thank you so much! One last thing, I can see there are other functions like `JSON.parse` for example, which is great since I am looking to use that. But is there any other document which talks list such functions?

**Comment by gokhan-berberoglu** [comment]
@ashwinnirantar

```javascript
function inTimeRange(beginHours, beginMinutes, endHours, endMinutes){}
function isDayOfWeek(days){}
function btoa(str){}
function atob(encodedStr){}
function httpGet(url, headers, timeout){}
function httpDelete(url, headers, timeout){}
function httpPost(url, data, contentType, headers, timeout){}
function httpPut(url, data, contentType, headers, timeout){}
function verifyJwt(token, publicKeyOrModulusBase64, exponentBase64){}
function auditLog(message){}
```

**Comment by ashwinnirantar** [comment]
@gokhan-berberoglu/ @danijeel Do you know how I can access environment variables in the user claim script?
