### ISSUE TITLE
appgatesdp_site data source doesn't error when multiple sites are returned from a site_name search

### ISSUE THREAD

**Issue by timvisher** [appgate/terraform-provider-appgatesdp#277]
### Terraform CLI, Terraform appgatesdp Provider Version, and Appgate Appliance version(s)

terraform cli: v1.3.6
terraform-provider-appgatesdp:  v1.0.4
appgate appliance version: 6.1.0

### Affected Resource(s)

* appgatesdp_site data source

### Terraform Configuration Files

~Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.~

```hcl
data "appgatesdp_site" "foo" {
  site_name: "foo"
}
```

### ~Debug Output~ 

N/A

### Panic Output

N/A

### Expected Behavior

If I have multiple Sites that match a name search, say `foo` and `foo-bar`, and I try to get a Site reference via `site_name`, the provider should error telling my that I have an ambiguous Site search or something.

For instance, the `aws_security_group` data source does the following in the same situation:

```
╷
│ Error: multiple EC2 Security Groups matched; use additional constraints to reduce matches to a single EC2 Security Group
│
```

### Actual Behavior

Instead it just silently selects the first result.

### Steps to Reproduce

N/A

**Comment by danijeel** [comment]
Closing this issue since this is fixed in [1.1.0](https://registry.terraform.io/providers/appgate/appgatesdp/1.1.0)
