### ISSUE TITLE
Version 1.1.1 missing URL in the state of a Client Profile

### ISSUE THREAD

**Issue by timvisher** [appgate/terraform-provider-appgatesdp#288]
### Terraform CLI, Terraform appgatesdp Provider Version, and Appgate Appliance version(s)

```
Terraform v1.3.9
on darwin_arm64
+ provider registry.terraform.io/appgate/appgatesdp v1.0.4
+ provider registry.terraform.io/hashicorp/local v2.3.0

Your version of Terraform is out of date! The latest version
is 1.4.4. You can update by downloading from https://www.terraform.io/downloads.html
```

appgate appliance version: 6.1.0

### Affected Resource(s)

* appgatesdp_client_profile

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "appgatesdp_client_profile" "charnock" {
  …
}

resource "local_file" "charnock_url" {
  content = appgatesdp_client_profile.charnock.url
  …
}
```

### Debug Output

```
╷
│ Error: Invalid Attribute Combination
│
│   with local_file.charnock_url,
│   …
│
│ No attribute specified when one (and only one) of [content,sensitive_content,content_base64] is required
╵
```

### Expected Behavior

Reference URL of the Client Profile.

### Actual Behavior

Null reference.

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

1.0.4 did not have this problem.

```
$ terraform state show appgatesdp_client_profile.foo
…
    url                    =
…
```

vs. 1.1.1

```
$ terraform state show appgatesdp_client_profile.foo
…
    <url missing>
…
```

### References

url is still listed in the docs https://registry.terraform.io/providers/appgate/appgate-sdp/latest/docs/resources/client_profile and is obviously still useful and relevant.

* #0000

**Comment by danijeel** [comment]
Thanks for reporting this issue, this will be available in the next release 1.1.2
