### ISSUE TITLE
Optional appgatesdp_appliance.logForwarder.tcpClients[0].filter argument producing an error

### ISSUE THREAD

**Issue by muram** [appgate/terraform-provider-appgatesdp#292]
### Terraform CLI, Terraform appgatesdp Provider Version, and Appgate Appliance version(s)

terraform cli: v1.4.4
terraform-provider-appgatesdp:  v1.1.1
appgate appliance version: 6.1.2-33110-release

### Affected Resource(s)

* appgatesdp_appliance

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "appgatesdp_appliance" "controller" {
    ...
    log_forwarder {
      enabled = true
  
      tcp_clients {
        name    = "Company SIEM"
        host    = "siem.company.com"
        port    = 601
        format  = "syslog"
        use_tls = true
      }
  
      sites = [
        data.appgatesdp_site.default_site.id
      ]
    }
  ...
}
```

### Expected Behavior

Ignore optional argument and don't display an error.

### Actual Behavior

![image](https://user-images.githubusercontent.com/20080955/231235912-85d77c6f-5fce-404b-a1bd-f3448737e1d8.png)

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by danijeel** [comment]
Thanks for reporting this issue, this will be available in the next release 1.1.2
