### ISSUE TITLE
Documentation consistency for appgatesdp_policy

### ISSUE THREAD

**Issue by jered-miller** [appgate/terraform-provider-appgatesdp#297]
### Terraform CLI, Terraform appgatesdp Provider Version, and Appgate Appliance version(s)

Terraform v1.3.7
on darwin_arm64

provider registry.terraform.io/appgate/appgatesdp v1.1.1
provider registry.terraform.io/hashicorp/aws v4.60.0
appgate appliance version: 6.1.2

### Affected Resource(s)

* appgatesdp_policy
* Documentation?

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "appgatesdp_policy" "this" {
  for_each = { for ap in var.access_policies : ap.name => ap }

  name      = each.value.name
  notes     = each.value.notes
  disabled  = !each.value.enabled

  type      = each.value.type

  entitlements = [ for e in each.value.entitlements : appgatesdp_entitlement.this[e].id ]

  expression = file("./policy_conditions/${each.value.condition_file}")

  tags      = each.value.tags
}
```

### Expected Behavior

Creating a policy with no type creates a “Mixed” policy.  This option is not available in the ui and I had to go digging through the API documentation to figure out why this was showing up.  `type=""` is marked optional/informational in the terraform provider documentation, but has actual effect.

```
[type](https://registry.terraform.io/providers/appgate/appgatesdp/latest/docs/resources/policy#type): (Optional) Type of the Policy. It is informational and not enforced.
```

### Actual Behavior

Documentation should reflect that not including the type param will create a mixed policy.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by danijeel** [comment]
Hi @jered-miller

The policy attribute `type` is a new attribute. The reason it's Optional is for backwards compatibility, and generated a value of `Mixed` if omitted.  

Certain policy attributes are only applicable for certain types, for example:

- access policy (type = "Access") is based on [Entitlements](https://registry.terraform.io/providers/appgate/appgatesdp/latest/docs/resources/entitlement) association
- admin policy  (type = "Admin")  is based on [admin role](https://registry.terraform.io/providers/appgate/appgatesdp/latest/docs/resources/administrative_role) association
- device policy  (type = "Device")  is based on [ringfence rule](https://registry.terraform.io/providers/appgate/appgatesdp/latest/docs/resources/ringfence_rule)
- DNS policy  (type = "Dns")  is based on DNS configuration or DNS entitlements.

so for example,
```hcl
resource "appgatesdp_administrative_role" "test_administrative_role" {
  name  = "tf-admin"
  privileges {
    type         = "Create"
    target       = "Entitlement"
    default_tags = ["api-created"]
  }
}

resource "appgatesdp_policy" "bad_example" {
  name = "Test policy"
  type = "Dns" # explicit set DNS type
  # DNS Type can't use administrative_roles
  administrative_roles = [
    appgatesdp_administrative_role.test_administrative_role.id
  ]
  tamper_proofing = false
  disabled        = false

  expression = <<-EOF
	var result = false;
	return result;
	EOF
}
```
this example would output validation error, administrativeRoles may not be used on this Policy type. 
but if you would omit `type = "Dns"` it would become a mixed type.

What we could do that may improve the user experience and make it more clear is to add additional terraform resources where the  `type`  is predefined, for  example:  

`resource "appgatesdp_access_policy" "policy" {}`   Policy type = Access
`resource "appgatesdp_admin_policy" "policy" {}`    Policy type = Admin
`resource "appgatesdp_device_policy" "policy" {}`   Policy type = Device
`resource "appgatesdp_dns_policy" "policy" {}`       Policy type = DNS

this would then be the same as shown in the admin UI when creating a policy
![Screenshot from 2023-04-17 15-10-24](https://user-images.githubusercontent.com/1218385/232494089-97efaa67-3136-42b0-b3b2-dcda31568d64.png)

**Comment by jered-miller** [comment]
I think breaking this into different resources would be a good idea.  Will close.

**Comment by danijeel** [comment]
@jered-miller  in [v1.4.0](https://github.com/appgate/terraform-provider-appgatesdp/releases/tag/v1.4.0) includes new resources

* `appgatesdp_device_policy` - https://registry.terraform.io/providers/appgate/appgatesdp/latest/docs/resources/device_policy
* `appgatesdp_dns_policy` - https://registry.terraform.io/providers/appgate/appgatesdp/latest/docs/resources/dns_policy
* `appgatesdp_access_policy`-  https://registry.terraform.io/providers/appgate/appgatesdp/latest/docs/resources/access_policy
* `appgatesdp_admin_policy` - https://registry.terraform.io/providers/appgate/appgatesdp/latest/docs/resources/admin_policy

hopefully this will make it somewhat more clear to use.
