### ISSUE TITLE
Bugs with appgatesdp_site

### ISSUE THREAD

**Issue by maxabaumgarten** [appgate/terraform-provider-appgatesdp#329]
1. The documentation is not clear and has mistakes.  There is no indication of the resources attribute types and requires guessing if something is supposed to be a block or a sub-block of other attributes.  There are [typos](https://registry.terraform.io/providers/appgate/appgatesdp/latest/docs/resources/site#use_iamrole)

2. The `state_sharing` description is wrong and/or misconfigured.  Documentation says [optional](https://registry.terraform.io/providers/appgate/appgatesdp/latest/docs/resources/site#name_resolution:~:text=state_sharing%3A%20(-,Optional,-)%20default%20value%20false)

Terraform Plan:
```
│ Error: Missing required argument
│ 
│   on sites.tf line 23, in resource "appgatesdp_site" "deliverr_use1":
│   23:   vpn {
│ 
│ The argument "state_sharing" is required, but no definition was found.
╵
```

3.  The `vpn` block does not function correctly.  My code:
```
  vpn {
    state_sharing = false
    snat          = false
  }
```

What terraform plan/apply does:
```
      ~ vpn {
          ~ snat                           = false -> true
            # (2 unchanged attributes hidden)


            # (2 unchanged blocks hidden)
        }
        # (1 unchanged block hidden)
    }
```

Plz fix and consider reviewing all the settings.

**Comment by mandopaloooza** [comment]
Thanks for reporting the issue @maxabaumgarten 

> 1. The documentation is not clear and has mistakes. There is no indication of the resources attribute types and requires guessing if something is supposed to be a block or a sub-block of other attributes. There are [typos](https://registry.terraform.io/providers/appgate/appgatesdp/latest/docs/resources/site#use_iamrole)
>
> 2. The state_sharing description is wrong and/or misconfigured. Documentation says [optional](https://registry.terraform.io/providers/appgate/appgatesdp/latest/docs/resources/site#name_resolution:~:text=state_sharing%3A%20(-,Optional,-)%20default%20value%20false)

I have updated the documentation in above mentioned PR. Since these docs are crafted manually, if you have any other documentation of resources that needs update, please ping me and I will try my best to assist you. 

> The vpn block does not function correctly
Apart from the documentation error about the type, I've verified that the `vpn` block is working as intended. Could you provide me the full `appgatesdp_site` resource you are trying to define?
