### ISSUE TITLE
Failed to refresh license state

### ISSUE THREAD

**Issue by hobietje** [appgate/terraform-provider-appgatesdp#94]
Minor issue, but the TF provider cannot refresh the state of an expired (trial) license.   We worked around this by updating the license manually in the web console.

```
[2021-03-22T22:47:08Z] Error: Failed to read license, parsing time ""-1000000000-01-01T00:00:00Z"" as ""2006-01-02T15:04:05Z07:00"": cannot parse "-1000000000-01-01T00:00:00Z"" as "2006"
```

AWS BYOL AMI: 5.3.2-23587-release
terraform-provider-appgate-sdp: 0.4.0
terraform: v0.14.4

**Comment by danijeel** [comment]
Thank you for your report, I'll investigate this.

**Comment by timvisher** [comment]
Also confirmed that it wasn't a whitespace issue with the license content. It looks like at least the import process isn't recording the license content correctly at all, instead making it 'null'.

```
{
  "mode": "managed",
  "type": "appgatesdp_license",
  "name": "licenses_001_initial_license",
  "provider": "provider[\"registry.terraform.io/appgate/appgatesdp\"]",
  "instances": [
    {
      "schema_version": 1,
      "attributes": {
        "id": "***_v2",
        "license": null,
        "timeouts": {
          "create": null,
          "delete": null,
          "update": null
        }
      },
      "sensitive_attributes": [],
      "private": "***"
    }
  ]
},
```
